Repository devops-kung-fu/bomber, pull requests merged in 2022-10, with the labels that each got.

#58 feat: License support
  .goreleaser.yaml
  .hookz.yaml
  .vscode/launch.json
  CONTRIBUTING.md
  README.md
  cmd/root.go
  cmd/scan.go
  formats/cyclonedx/cyclonedx.go
  formats/spdx/spdx.go
  formats/syft/syft.go
  go.mod
  go.sum
  img/bomber-example.png
  img/bomber-html.png
  img/bomber-json.png
  lib/bomloader.go
  lib/bomloader_test.go
  models/structs.go
  providers/ossindex/OSSIndex.go
  providers/ossindex/OSSIndex_test.go
  providers/osv/osv.go
  providers/osv/osv_test.go
  renderers/html/html.go
  renderers/html/html_test.go
  renderers/json/json_test.go
  renderers/stdout/stdout.go
  sbom/bomber.cyclonedx.json
  sbom/test/bomber.spdx.json
  sbom/test/bomber.syft.json
  sbom/test/juiceshop.cyclonedx.json
  test.json
Labels: bug, enhancement

#63 fix: licenseDeclared is not slice
  formats/spdx/spdx.go
Labels: go

#69 feat: add Snyk provider
  go.mod
  go.sum
  providers/providerfactory.go
  providers/providerfactory_test.go
  providers/snyk/client.go
  providers/snyk/jsonapi.go
  providers/snyk/orgid.go
  providers/snyk/orgid_test.go
  providers/snyk/snyk.go
  providers/snyk/snyk_test.go
  providers/snyk/testdata/snyk_package_issues_response.json
  providers/snyk/testdata/snyk_self_response.json
  providers/snyk/vulns.go
  providers/snyk/vulns_test.go
Labels: enhancement

#72 feat: Renders and sanitizes Markdown vuln descriptions to HTML
  .vscode/launch.json
  cmd/root.go
  go.mod
  go.sum
  providers/ossindex/OSSIndex.go
  providers/snyk/vulns.go
  renderers/html/html.go
  sbom/bomber.cyclonedx.json
Labels: bug, enhancement, security
